USE CUSTOM_BASE_2
GO

/*

ALTER TABLE FLIGHT
ADD NUM_PASS INT

ALTER TABLE AGENCY
ADD NUM_BOOK INT DEFAULT 0

CREATE TRIGGER TR_BOOKING_INCREMENT_CUSTOMERS 
ON BOOKING
AFTER INSERT AS
	UPDATE FLIGHT
	SET NUM_PASS += 1
	FROM INSERTED
	WHERE FNUMBER = FLIGHT_NUMBER
	UPDATE AGENCY
	SET NUM_BOOK += 1
	FROM INSERTED
	WHERE NAME = AGENCY

CREATE TRIGGER TR_BOOKING_DECREMENT_CUSTOMERS 
ON BOOKING
AFTER DELETE AS
	UPDATE FLIGHT
	SET NUM_PASS -= 1
	FROM INSERTED
	WHERE FNUMBER = FLIGHT_NUMBER
	UPDATE AGENCY
	SET NUM_BOOK -= 1
	FROM INSERTED
	WHERE NAME = AGENCY

*/

CREATE TRIGGER TR_BOOKING_DECREMENT_CUSTOMERS 
ON BOOKING
AFTER UPDATE AS