use movies

/*SELECT STARNAME
FROM STARSIN 
	JOIN MOVIESTAR
	ON STARNAME = NAME
	WHERE MOVIETITLE = 'The Usual Suspects'
	AND GENDER = 'M';

SELECT STARNAME 
FROM STARSIN
	JOIN MOVIE
	ON MOVIETITLE = TITLE
	WHERE MOVIEYEAR = 1995
	AND STUDIONAME = 'MGM'

SELECT DISTINCT NAME
FROM MOVIEEXEC
	JOIN MOVIE
	ON CERT# = PRODUCERC#
	WHERE STUDIONAME = 'MGM'

SELECT M1.TITLE
FROM MOVIE M1
	JOIN MOVIE M2
	ON M2.TITLE = 'Star Wars'
	WHERE M1.LENGTH > M2.LENGTH

SELECT E1.NAME
FROM MOVIEEXEC E1
	JOIN MOVIEEXEC E2
	ON E2.NAME = 'Stephen Spielberg'
	WHERE E1.NETWORTH > E2.NETWORTH

SELECT TITLE
FROM MOVIE
	JOIN MOVIEEXEC E1
	ON PRODUCERC# = CERT#
		JOIN MOVIEEXEC E2
		ON E2.NAME = 'Stephen Spielberg'
		WHERE E1.NETWORTH > E2.NETWORTH*/