use ships

/*SELECT NAME
FROM SHIPS
	JOIN CLASSES
	ON SHIPS.CLASS = CLASSES.CLASS
		WHERE DISPLACEMENT > 50000

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS
	JOIN CLASSES
	ON SHIPS.CLASS = CLASSES.CLASS
		JOIN OUTCOMES
		ON SHIPS.NAME = OUTCOMES.SHIP
			WHERE BATTLE = 'Guadalcanal'

SELECT COUNTRY
FROM CLASSES
GROUP BY COUNTRY
HAVING COUNT(TYPE) = 2*/

SELECT *
FROM BATTLES

SELECT *
FROM OUTCOMES
JOIN BATTLES
ON BATTLES.NAME = OUTCOMES.BATTLE
WHERE RESULT = 'damaged'

SELECT *
FROM OUTCOMES
ORDER BY BATTLE;

WITH CTE_INFO AS (
SELECT *
FROM OUTCOMES
) SELECT *
FROM CTE_INFO
