Use movies;

/*SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE (LENGTH > 120
OR LENGTH IS NULL)
AND YEAR < 2000

SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%'
AND BIRTHDATE > 1948
ORDER BY NAME DESC

SELECT STUDIONAME, COUNT(DISTINCT STARNAME)
FROM STARSIN
JOIN MOVIE
ON MOVIE.TITLE = STARSIN.MOVIETITLE
GROUP BY STUDIONAME

SELECT STARNAME, COUNT(MOVIETITLE)
FROM STARSIN
GROUP BY STARNAME

SELECT STUDIONAME, MAX(TITLE), MAX(YEAR)
FROM MOVIE
GROUP BY STUDIONAME

WITH MALE_STARS AS (
	SELECT *
	FROM MOVIESTAR
	WHERE GENDER = 'M'
)
 
SELECT *
FROM MALE_STARS
WHERE BIRTHDATE = (
	SELECT MAX(BIRTHDATE)
	FROM MALE_STARS
 )

SELECT STUDIONAME, STARNAME, COUNT(MOVIETITLE)
FROM STARSIN 
JOIN MOVIE M
ON MOVIETITLE = TITLE
WHERE STARNAME = (
	SELECT STARNAME
	FROM (
		SELECT TOP (1) STARNAME, COUNT(STARNAME) as "STARCOUNT"
		FROM STARSIN 
		JOIN MOVIE
		ON MOVIETITLE = TITLE
		WHERE STUDIONAME = M.STUDIONAME
		GROUP BY STARNAME
		ORDER BY "STARCOUNT" DESC
	) CN
)
GROUP BY STUDIONAME, STARNAME;

SELECT TITLE, YEAR, COUNT(STARNAME) AS NUM_ACTORS
FROM MOVIE
JOIN STARSIN
ON STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY TITLE, YEAR
HAVING COUNT(STARNAME) > 2*/