USE ships

/*SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP LIKE '[CK]%'

SELECT NAME, COUNTRY
FROM SHIPS
JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS
WHERE NAME NOT IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'sunk'
)
ORDER BY NAME



SELECT BATTLE 
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) > (
	SELECT COUNT(*)
	FROM OUTCOMES
	WHERE BATTLE = 'Guadalcanal'
)

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.CLASS IN (
	SELECT CLASS
	FROM CLASSES
	WHERE DISPLACEMENT = (
		SELECT MIN(DISPLACEMENT)
		FROM CLASSES 
	)
	AND NUMGUNS =
	(
		SELECT MAX(NUMGUNS)
		FROM CLASSES
		WHERE DISPLACEMENT =
		(
			SELECT MIN(DISPLACEMENT)
			FROM CLASSES
		)
	)
)

SELECT COUNT(DISTINCT SHIP)
FROM OUTCOMES
WHERE SHIP IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'damaged'
)
AND SHIP IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'ok'
)

SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'damaged'
)
AND SHIP IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'ok'
)*/

-- Try with union
SELECT COUNTRY, COUNT(SHIP)
FROM CLASSES
LEFT JOIN SHIPS
ON SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES
ON OUTCOMES.SHIP = SHIPS.NAME
WHERE RESULT = 'sunk' 
OR RESULT IS NULL 
GROUP BY COUNTRY, RESULT