USE movies

/*SELECT TITLE, NAME
FROM MOVIE
JOIN MOVIEEXEC
ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE CERT# IN (
	SELECT PRODUCERC#
	FROM MOVIE
	WHERE TITLE = 'Star Wars')

SELECT NAME
FROM MOVIEEXEC
WHERE CERT# IN (
	SELECT PRODUCERC#
	FROM MOVIE
	WHERE TITLE IN (
		SELECT MOVIETITLE
		FROM STARSIN
		WHERE STARNAME = 'Harrison Ford'))

SELECT DISTINCT STUDIONAME, STARNAME
FROM MOVIE
JOIN STARSIN
ON MOVIE.TITLE = STARSIN.MOVIETITLE
WHERE MOVIE.TITLE IN (
	SELECT MOVIETITLE
	FROM STARSIN)

SELECT STARNAME, NETWORTH, TITLE
FROM STARSIN
JOIN MOVIE
ON STARSIN.MOVIETITLE = MOVIE.TITLE
JOIN MOVIEEXEC
ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE NETWORTH = (
	SELECT MAX(NETWORTH)
	FROM MOVIEEXEC)
ORDER BY TITLE

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (
	SELECT STARNAME
	FROM STARSIN)*/