USE ships;

/*SELECT *
FROM SHIPS
JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS
ORDER BY NAME

SELECT *
FROM SHIPS
RIGHT JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS
ORDER BY NAME

SELECT COUNTRY, NAME
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE NAME NOT IN (
	SELECT SHIP
	FROM OUTCOMES
)
ORDER BY COUNTRY

SELECT NAME AS 'Ship Name'
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE LAUNCHED = 1916
AND NUMGUNS >= 7

SELECT SHIP , BATTLE, DATE
FROM OUTCOMES
JOIN BATTLES
ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE RESULT = 'sunk'
ORDER BY BATTLE

SELECT NAME, DISPLACEMENT, LAUNCHED
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE NAME = CLASSES.CLASS

SELECT *
FROM CLASSES
WHERE CLASS NOT IN (
	SELECT CLASS
	FROM SHIPS
)

SELECT NAME, DISPLACEMENT, NUMGUNS, RESULT
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
JOIN OUTCOMES
ON SHIPS.NAME = OUTCOMES.SHIP
WHERE BATTLE = 'North Atlantic'
ORDER BY NAME*/