USE CUSTOM_BASE
GO

/*

CREATE TABLE USERS (
	ID INT NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(30),
	PASSWORD VARCHAR(30),
	REGISTRATION_DATE DATE
);

CREATE TABLE GROUPS (
	ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(25),
	DESCIPTION VARCHAR(100) DEFAULT ''
)


CREATE TABLE FRIENDS (
	FRIEND_ID_1 INT NOT NULL 
	FOREIGN KEY REFERENCES USERS(ID),
	FRIEND_ID_2 INT NOT NULL 
	FOREIGN KEY REFERENCES USERS(ID),
)

CREATE TABLE WALLS (
	USER_ID INT NOT NULL FOREIGN KEY REFERENCES USERS(ID), 
	COMMENTER_ID INT NOT NULL,
	COMMENT_TEXT VARCHAR(1000),
	COMMENT_DATE DATE
)

CREATE TABLE GROUPS (
	ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(25),
	DESCIPTION VARCHAR(100) DEFAULT ''
)

CREATE TABLE GROUP_MEMBERS (
	GROUP_ID INT NOT NULL 
	FOREIGN KEY REFERENCES GROUPS(ID)
	ON DELETE CASCADE,
	MEMBER_ID INT NOT NULL 
	FOREIGN KEY REFERENCES USERS(ID)
	ON DELETE CASCADE
)

INSERT INTO USERS
VALUES (1, 'vejexev858@gmail.com', 'bestPASSever', GETDATE())

INSERT INTO USERS
VALUES (2, 'cthulhu@gmail.com', 'qwd43%^@!13', GETDATE())

INSERT INTO USERS
VALUES (3, 'todorflorida@abv.bg', 'pepelnik', GETDATE())

INSERT INTO FRIENDS 
VALUES (1, 2)

INSERT INTO WALLS 
VALUES (1, 2, '“The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown”', GETDATE())

INSERT INTO GROUPS
VALUES (1, 'CTHULLU CULT', 'Fans of the fantastic tale of cthullu by H.P Lovecraft')

INSERT INTO GROUPS
VALUES (2, 'IDK', 'A group of like-minded people')

INSERT INTO GROUP_MEMBERS
VALUES (1, 2)

INSERT INTO GROUP_MEMBERS
VALUES (2, 3)

*/