USE CUSTOM_BASE
GO

/*CREATE TABLE PRODUCT (
	MODEL VARCHAR(4),
	MAKER VARCHAR(1),
	TYPE VARCHAR(7)
)

CREATE TABLE PRINTER (
	CODE INT,
	MODEL VARCHAR (4),
	PRICE DECIMAL (10,2)
	PRIMARY KEY (CODE)
)

INSERT INTO PRODUCT
VALUES ('1234', 'A', 'PC')

INSERT INTO PRODUCT
VALUES ('6666', 'D', 'Laptop')

INSERT INTO PRINTER
VALUES (1 , '3819', 999.99)

ALTER TABLE PRINTER
ADD 
TYPE VARCHAR(6)
CONSTRAINT CHK_TYPE CHECK (TYPE IN ('laser', 'matrix', 'jet')),
COLOR VARCHAR(1) DEFAULT 'n' 
CONSTRAINT CHK_COLOR CHECK (COLOR IN ('y', 'n'))

ALTER TABLE PRINTER
DROP COLUMN PRICE

DROP TABLE PRODUCT
DROP TABLE PRINTER*/