USE CUSTOM_BASE_2
GO

/*
CREATE VIEW vw_FLIGHT_INFO AS
SELECT 
AIRLINE_OPERATOR,
FNUMBER,
FLIGHT_NUMBER,
COUNT(STATUS) AS CONFIRMED_CUSTOMERS
FROM FLIGHT
JOIN BOOKING
ON FLIGHT_NUMBER = FNUMBER
WHERE STATUS = 1
GROUP BY 
AIRLINE_OPERATOR,
FNUMBER,
FLIGHT_NUMBER;

CREATE VIEW vw_SF_AGENCIES AS
SELECT *
FROM AGENCY
WHERE CITY = 'Sofia'
WITH CHECK OPTION

CREATE VIEW vw_PH_NULL_AGENCIES AS
SELECT *
FROM AGENCY
WHERE PHONE IS NULL
WITH CHECK OPTION

INSERT INTO vw_SF_AGENCIES 
VALUES('T1 Tour', 'Bulgaria', 'Sofia','+359');

INSERT INTO vw_PH_NULL_AGENCIES 
VALUES('T2 Tour', 'Bulgaria', 'Sofia',null);

INSERT INTO vw_SF_AGENCIES 
VALUES('T3 Tour', 'Bulgaria', 'Varna','+359');

INSERT INTO vw_PH_NULL_AGENCIES 
VALUES('T4 Tour', 'Bulgaria', 'Varna',null);

INSERT INTO vw_PH_NULL_AGENCIES 
VALUES('T4 Tour', 'Bulgaria', 'Sofia','+359');*/