USE movies

/*INSERT INTO MOVIESTAR (NAME, GENDER, BIRTHDATE)
VALUES ('Nicole Kidman', 'F', '1967-06-20');

DELETE FROM MOVIEEXEC
WHERE NETWORTH < 30000000;

DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL;*/
