USE ships

/*INSERT INTO CLASSES (CLASS, TYPE, COUNTRY, BORE, DISPLACEMENT)
VALUES ('Nelson', 'bb', 'Gt.Britain', 16, 34000)

INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927)

INSERT INTO SHIPS
VALUES ('Rodney', 'Nelson', 1927)

 DELETE FROM SHIPS
 WHERE NAME IN (
	SELECT SHIP
	FROM OUTCOMES
	WHERE RESULT = 'sunk'
)

UPDATE CLASSES
SET BORE *= 2.5, DISPLACEMENT *= 1.1*/