USE ships

/*
DELETE FROM OUTCOMES
WHERE BATTLE IN (
	SELECT BATTLE
	FROM (
		SELECT BATTLE, COUNT(SHIP) AS SHIPCOUNT
		FROM BATTLES
		LEFT JOIN OUTCOMES
		ON OUTCOMES.BATTLE = BATTLES.NAME
		GROUP BY BATTLE
	) CTX
	WHERE SHIPCOUNT = 1
)

INSERT INTO outcomes VALUES ('Missouri','Surigao Strait', 'sunk'),
('Missouri','North Cape', 'sunk'),
('Missouri','North Atlantic', 'ok');

DELETE FROM OUTCOMES
WHERE 
RESULT = 'sunk'
AND SHIP IN
(
	SELECT SHIP
	FROM
	(
		SELECT SHIP, COUNT(BATTLE)AS SUNKCOUNT
		FROM OUTCOMES
		WHERE RESULT = 'sunk'
		GROUP BY SHIP
	) CTX
	WHERE SUNKCOUNT >= 2
)

SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS
ON SHIPS.NAME = OUTCOMES.SHIP
JOIN CLASSES 
ON CLASSES.CLASS = SHIPS.CLASS
WHERE COUNTRY IN (
	SELECT DISTINCT COUNTRY
	FROM CLASSES
	JOIN SHIPS
	ON CLASSES.CLASS = SHIPS.CLASS
	JOIN OUTCOMES 
	ON OUTCOMES.SHIP = SHIPS.NAME
	WHERE BATTLE = 'Guadalcanal'
)
AND BATTLE != 'Guadalcanal'
*/