use movies

/*SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'F'
AND NAME IN 
	(SELECT NAME 
	FROM MOVIEEXEC
	WHERE NETWORTH > 1000000)

SELECT NAME 
FROM MOVIESTAR
WHERE NAME NOT IN 
	(SELECT NAME 
	FROM MOVIEEXEC)
ORDER BY NAME

SELECT TITLE
FROM MOVIE 
WHERE MOVIE.LENGTH > 
	(SELECT LENGTH
	FROM MOVIE
	WHERE TITLE = 'Star Wars')

SELECT TITLE, NAME
FROM MOVIE
JOIN MOVIEEXEC
ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE NETWORTH > (
	SELECT NETWORTH
	FROM MOVIEEXEC
	WHERE NAME = 'Merv Griffin')*/