USE ships

/*SELECT COUNT(CLASS)
FROM CLASSES

SELECT AVG(NUMGUNS)
FROM CLASSES

SELECT AVG(NUMGUNS)
FROM SHIPS
JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS

SELECT COUNTRY, AVG(BORE)
FROM CLASSES
JOIN SHIPS
ON SHIPS.CLASS = CLASSES.CLASS
GROUP BY COUNTRY*/